export const DEFAULT_RESTAURANTS = [
  // --- VEG RESTAURANTS (10) ---
  {
    name: 'Saffron Court',
    code: 'SC',
    location: 'Connaught Place, New Delhi',
    tagline: 'Royal North Indian dining with candlelit private rooms.',
    description: 'A polished dining room for slow dinners, rich curries, and chef-led tasting menus.',
    cuisineTags: ['North Indian', 'Tandoor', 'Chef Specials'],
    image: { url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 1,
  },
  {
    name: 'Pure Joy',
    code: 'PJ',
    location: 'Bandra Reclamation, Mumbai',
    tagline: 'Authentic South Indian delights and filter coffee.',
    description: 'A cozy spot for crispy dosas, fluffy idlis, and traditional South Indian meals.',
    cuisineTags: ['South Indian', 'Breakfast', 'Comfort Food'],
    image: { url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 2,
  },
  {
    name: 'Gardenia',
    code: 'GD',
    location: 'Koregaon Park, Pune',
    tagline: 'Farm-to-table vegetarian feast in a lush garden.',
    description: 'Enjoy organic vegetables and artisanal breads in a serene outdoor setting.',
    cuisineTags: ['Continental', 'Organic', 'Family Dining'],
    image: { url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 3,
  },
  {
    name: 'Satvik Rasoi',
    code: 'SR',
    location: 'Assi Ghat, Varanasi',
    tagline: 'Traditional Satvik food by the holy Ganges.',
    description: 'Experience the purity of traditional Indian cuisine with no onion or garlic.',
    cuisineTags: ['Traditional', 'North Indian', 'Spiritual'],
    image: { url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 4,
  },
  {
    name: 'Green Bowl',
    code: 'GB',
    location: 'Indiranagar, Bengaluru',
    tagline: 'Modern healthy bowls and cold-pressed juices.',
    description: 'Fuel your day with nutrient-rich bowls, salads, and healthy snacks.',
    cuisineTags: ['Healthy', 'Salads', 'Juices'],
    image: { url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 5,
  },
  {
    name: 'The Vegan Way',
    code: 'VW',
    location: 'MG Road, Bengaluru',
    tagline: '100% plant-based innovative cuisine.',
    description: 'Explore creative vegan dishes that are both delicious and ethical.',
    cuisineTags: ['Vegan', 'Fusion', 'Eco-friendly'],
    image: { url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 6,
  },
  {
    name: 'Sprout & Co',
    code: 'SC2',
    location: 'HSR Layout, Bengaluru',
    tagline: 'Fresh sprouts and high-protein vegetarian meals.',
    description: 'A perfect spot for fitness enthusiasts and health-conscious diners.',
    cuisineTags: ['Protein-rich', 'Healthy', 'Fitness'],
    image: { url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 7,
  },
  {
    name: 'Nature\'s Plate',
    code: 'NP',
    location: 'Sector 17, Chandigarh',
    tagline: 'Traditional Punjabi vegetarian food with a modern twist.',
    description: 'Rich dal makhani, paneer tikka, and buttery naans in a stylish setting.',
    cuisineTags: ['Punjabi', 'North Indian', 'Gourmet'],
    image: { url: 'https://images.unsplash.com/photo-1601050638917-3d903006d933?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 8,
  },
  {
    name: 'Herbivore House',
    code: 'HH',
    location: 'Fort Kochi, Kochi',
    tagline: 'Coastal vegetarian delights with local spices.',
    description: 'Discover the unique flavors of Kerala\'s vegetarian heritage.',
    cuisineTags: ['Kerala', 'South Indian', 'Coastal'],
    image: { url: 'https://images.unsplash.com/photo-1567337710282-00832b415979?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 9,
  },
  {
    name: 'The Green Fork',
    code: 'TGF',
    location: 'Jubilee Hills, Hyderabad',
    tagline: 'Upscale vegetarian fine dining.',
    description: 'Exquisite multi-cuisine vegetarian dishes served with elegance.',
    cuisineTags: ['Fine Dining', 'Multi-cuisine', 'Gourmet'],
    image: { url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80' },
    diet: 'Veg',
    sortOrder: 10,
  },

  // --- NON-VEG RESTAURANTS (10) ---
  {
    name: 'Harbor Flame',
    code: 'HF',
    location: 'Bandra Reclamation, Mumbai',
    tagline: 'Coastal grills, seafood platters, and sunset terrace tables.',
    description: 'An energetic waterfront branch built for seafood nights, cocktails, and larger groups.',
    cuisineTags: ['Seafood', 'Grill', 'Cocktails'],
    image: { url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 11,
  },
  {
    name: 'Meat & Greet',
    code: 'MG',
    location: 'Connaught Place, New Delhi',
    tagline: 'The ultimate destination for meat lovers.',
    description: 'Juicy steaks, succulent kebabs, and hearty meat platters.',
    cuisineTags: ['Steaks', 'Kebabs', 'Grill'],
    image: { url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 12,
  },
  {
    name: 'The Steak House',
    code: 'TSH',
    location: 'Bandra West, Mumbai',
    tagline: 'Premium steaks and aged wines.',
    description: 'Expertly grilled steaks served with artisanal sides and vintage wines.',
    cuisineTags: ['Steakhouse', 'Gourmet', 'Wine'],
    image: { url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 13,
  },
  {
    name: 'Chicken Coop',
    code: 'CC',
    location: 'Hinjewadi, Pune',
    tagline: 'Everything chicken, from fried to grilled.',
    description: 'A casual spot for chicken burgers, wings, and rotisserie chicken.',
    cuisineTags: ['Chicken', 'Fast Food', 'Casual'],
    image: { url: 'https://images.unsplash.com/photo-1567620985032-074b02323fd2?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 14,
  },
  {
    name: 'Grill Master',
    code: 'GM',
    location: 'Whitefield, Bengaluru',
    tagline: 'Masterfully grilled meats and smokey flavors.',
    description: 'Experience the art of BBQ with our slow-smoked meats and secret sauces.',
    cuisineTags: ['BBQ', 'Smoked Meats', 'Grill'],
    image: { url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 15,
  },
  {
    name: 'Royal Biryani',
    code: 'RB',
    location: 'Gachibowli, Hyderabad',
    tagline: 'Authentic Hyderabadi biryani for royalty.',
    description: 'Fragrant long-grain rice with tender meat and aromatic spices.',
    cuisineTags: ['Biryani', 'Hyderabadi', 'Indian'],
    image: { url: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 16,
  },
  {
    name: 'Tandoori Nights',
    code: 'TN',
    location: 'Hazratganj, Lucknow',
    tagline: 'The best of Awadhi kebabs and tandoori dishes.',
    description: 'Melt-in-your-mouth kebabs and rich curries from the heart of Lucknow.',
    cuisineTags: ['Awadhi', 'Mughlai', 'Tandoor'],
    image: { url: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 17,
  },
  {
    name: 'Coastal Flavors',
    code: 'CF',
    location: 'Candolim, Goa',
    tagline: 'Fresh seafood and Goan spices.',
    description: 'Enjoy the catch of the day with our signature Goan curry and local flavors.',
    cuisineTags: ['Seafood', 'Goan', 'Coastal'],
    image: { url: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 18,
  },
  {
    name: 'The Burger Joint',
    code: 'TBJ',
    location: 'Saket, New Delhi',
    tagline: 'Gourmet burgers with loaded toppings.',
    description: 'Crafted burgers with premium patties and creative flavor combinations.',
    cuisineTags: ['Burgers', 'American', 'Casual'],
    image: { url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 19,
  },
  {
    name: 'Fish Market',
    code: 'FM',
    location: 'T. Nagar, Chennai',
    tagline: 'Premium seafood experience.',
    description: 'A wide range of seafood prepared in various traditional and modern styles.',
    cuisineTags: ['Seafood', 'Gourmet', 'Coastal'],
    image: { url: 'https://images.unsplash.com/photo-1534080564607-198f9dd5d61a?auto=format&fit=crop&w=800&q=80' },
    diet: 'Non-Veg',
    sortOrder: 20,
  },
];
